"""
SupaGuard Git Zero-Leak Guard
Installs ultra-fast (<15ms) pre-commit and pre-push hooks to block accidental credential leaks.
"""

import sys
import os
import subprocess
from pathlib import Path

HOOK_SCRIPT_CONTENT = """#!/bin/sh
# --- SupaGuard Zero-Leak Git Hook ---
# Auto-generated by supaguard hook install

if [ -n "$SKIP_SUPAGUARD" ] || [ -n "$SKIP_ANTIVIRUS" ]; then
    exit 0
fi

if command -v supaguard >/dev/null 2>&1; then
    supaguard hook check-staged
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        echo ""
        echo "\033[1;31m[SUPAGUARD BLOCKED COMMIT]\033[0m Staged files contain security violations or leaked credentials."
        echo "\033[2mTo bypass intentionally, run: git commit --no-verify\033[0m"
        echo ""
        exit 1
    fi
elif command -v npx >/dev/null 2>&1; then
    npx @dev_apus/supaguard hook check-staged
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        exit 1
    fi
fi
exit 0
"""

def get_git_repos(target_dir: Path, recurse: bool = False):
    repos = []
    if (target_dir / ".git").is_dir():
        repos.append(target_dir)
        if not recurse:
            return repos

    for root, dirs, _ in os.walk(target_dir):
        if ".git" in dirs:
            repos.append(Path(root))
            dirs.remove(".git")
    return repos

def install_hooks(target_dir: Path, recurse: bool = False):
    repos = get_git_repos(target_dir, recurse)
    if not repos:
        print(f"\033[93m[WARN] No Git repositories found under '{target_dir}'.\033[0m")
        return

    count = 0
    for repo in repos:
        hooks_dir = repo / ".git" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        pre_commit = hooks_dir / "pre-commit"
        pre_push = hooks_dir / "pre-push"

        for hook_file in [pre_commit, pre_push]:
            hook_file.write_text(HOOK_SCRIPT_CONTENT)
            hook_file.chmod(0o755)
        print(f"\033[92m[OK] Installed Zero-Leak hooks:\033[0m {repo.name} ({hooks_dir})")
        count += 1
    print(f"\n\033[1;92mSuccessfully protected {count} repository(ies) with SupaGuard pre-commit hooks.\033[0m\n")

def uninstall_hooks(target_dir: Path, recurse: bool = False):
    repos = get_git_repos(target_dir, recurse)
    count = 0
    for repo in repos:
        hooks_dir = repo / ".git" / "hooks"
        for h_name in ["pre-commit", "pre-push"]:
            h_file = hooks_dir / h_name
            if h_file.exists() and ("SupaGuard Zero-Leak Git Hook" in h_file.read_text(errors="ignore") or "Antivirus Zero-Leak" in h_file.read_text(errors="ignore")):
                h_file.unlink()
                count += 1
        print(f"\033[93m- Removed hooks from:\033[0m {repo.name}")
    print(f"\n\033[1;93mUninstalled hooks from {count} file(s).\033[0m\n")

def check_staged_files():
    try:
        proc = subprocess.run(["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc.returncode != 0:
            sys.exit(0)
        
        staged_files = [f.strip() for f in proc.stdout.splitlines() if f.strip()]
        if not staged_files:
            sys.exit(0)

        from supaguard import core_engine

        violations = []
        for file_str in staged_files:
            file_path = Path(file_str)
            if file_path.exists() and file_path.is_file():
                findings = core_engine.scan_file_heuristics(file_path)
                for f in findings:
                    if f.get("severity") in ["CRITICAL", "HIGH", "MEDIUM"]:
                        violations.append(f)

        if violations:
            print("\n\033[1;41;97m [SUPAGUARD SECURITY ALERT] Staged Changes Contain Critical Threats / Secrets \033[0m")
            for idx, v in enumerate(violations, 1):
                print(f"  #{idx} \033[1;91m[{v['severity']}]\033[0m \033[1m{v['name']}\033[0m")
                print(f"     File:    {v['file']}:{v['line']}")
                print(f"     Snippet: \033[91m{v.get('snippet', '')}\033[0m")
                print(f"     Detail:  {v['desc']}")
            print("")
            sys.exit(1)
        else:
            sys.exit(0)
    except Exception:
        sys.exit(0)
